"""Run the synthetic native Android/CLI contract against an installed test APK.

Requires Python 3.12+, adb, Cargo and the adjacent MDBX checkout. Never uses a
person's vault: --fixture must be generated by the CLI contract fixture test.
"""
import argparse
import io
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tarfile
import tempfile
import uuid


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--package", required=True)
    parser.add_argument("--serial", required=True)
    parser.add_argument("--adb", default="adb")
    parser.add_argument("--toolchain", help="Optional rustup toolchain, without leading +")
    args = parser.parse_args()
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+", args.package):
        parser.error("invalid Android package")
    manifest = json.loads((args.fixture / "manifest.json").read_text(encoding="utf-8"))
    if manifest.get("password") != "Synthetic cross-client contract 20260928!" or "android" not in manifest:
        parser.error("expected the current synthetic contract fixture")
    if args.output.exists():
        parser.error("output must be a new directory")
    adb = [args.adb, "-s", args.serial]

    def run(*command, **kwargs):
        return subprocess.run(command, check=True, **kwargs)

    activity = run(*adb, "shell", "dumpsys", "activity", capture_output=True).stdout
    if b"Active instrumentation" in activity or b"mActiveInstrumentation" in activity:
        parser.error("another instrumentation is active; retry after it finishes")
    token = "monica-contract-" + uuid.uuid4().hex
    remote_tar = "/data/local/tmp/" + token + ".tar"
    relative = "files/" + token
    private_root = "/data/user/0/" + args.package + "/" + relative
    args.output.mkdir(parents=True)
    try:
        with tempfile.TemporaryDirectory(prefix="monica-contract-") as temp:
            archive = Path(temp) / "fixture.tar"
            with tarfile.open(archive, "w", format=tarfile.USTAR_FORMAT) as tar:
                tar.add(args.fixture, arcname=relative + "/input")
            run(*adb, "push", str(archive), remote_tar, capture_output=True)
            run(*adb, "shell", "run-as", args.package, "tar", "xf", remote_tar, capture_output=True)
        result = run(
            *adb, "shell", "am", "instrument", "-w", "-r",
            "-e", "class", "takagi.ru.monica.repository.MdbxCliContractInstrumentedTest",
            "-e", "monicaContractInputDir", private_root + "/input",
            "-e", "monicaContractOutputDir", private_root + "/output",
            args.package + ".test/androidx.test.runner.AndroidJUnitRunner",
            capture_output=True,
        )
        (args.output / "instrumentation.log").write_bytes(result.stdout + result.stderr)
        if b"OK (1 test)" not in result.stdout or b"FAILURES!!!" in result.stdout:
            raise RuntimeError("Android contract failed; see instrumentation.log")
        result = run(*adb, "exec-out", "run-as", args.package, "tar", "cf", "-", "-C", relative + "/output", ".", capture_output=True)
        with tarfile.open(fileobj=io.BytesIO(result.stdout)) as tar:
            if any(not (item.isfile() or item.isdir()) for item in tar.getmembers()):
                raise RuntimeError("unexpected non-file output")
            tar.extractall(args.output, filter="data")
        # The verifier's authority is the original host input, never a manifest
        # or expected payload produced by Android.
        shutil.copy2(args.fixture / "manifest.json", args.output / "manifest.json")
        cargo = ["cargo"] + (["+" + args.toolchain] if args.toolchain else [])
        env = dict(os.environ, MONICA_CONTRACT_RETURN_DIR=str(args.output.resolve()))
        with (args.output / "cli-return.log").open("wb") as log:
            run(*cargo, "test", "--lib", "android_returned_contract", "--locked", "--", "--ignored",
                cwd=Path(__file__).resolve().parents[1], env=env, stdout=log, stderr=subprocess.STDOUT)
        print("Android roundtrip and CLI corruption controls passed:", args.output)
    finally:
        # Both targets are unique names created by this run, inside fixed test
        # directories. Never remove an existing app's other files.
        subprocess.run(adb + ["shell", "run-as", args.package, "rm", "-rf", relative], check=False, capture_output=True)
        subprocess.run(adb + ["shell", "rm", "-f", remote_tar], check=False, capture_output=True)


if __name__ == "__main__":
    main()
